logging:
   level:
      org:
         hibernate:
            type: debug
         springframework:
            cloud:
               config:
                  client: trace
            orm:
               jpa: trace
            jdbc: trace
            transaction: trace
eureka:
   instance:
      prefer-ip-address: true
   client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
         defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
